CREATE TABLE IF NOT EXISTS Schedule (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ReminderID BIGINT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DispatchTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    Version INT DEFAULT 1,
    FOREIGN KEY (ReminderID) REFERENCES Reminder(ID) ON DELETE CASCADE
);

CREATE INDEX dispatch_time_idx ON Schedule(DispatchTime);