
CREATE TABLE IF NOT EXISTS Password (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    Hash BLOB,
    Salt BLOB,
    UserID BIGINT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Version INT
);

CREATE INDEX idx_password_userid ON Password(UserID);
