CREATE TABLE IF NOT EXISTS ActivationToken (
 ID BIGINT PRIMARY KEY AUTO_INCREMENT,
 UserID BIGINT NOT NULL,
 Token VARCHAR(22) NOT NULL,
 CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
 UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 IsProcessed BOOLEAN DEFAULT FALSE,
 FOREIGN KEY (UserID) REFERENCES User(ID) ON DELETE CASCADE
);



