CREATE TABLE IF NOT EXISTS Reminder (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(255) NOT NULL,
    Content TEXT,
    UserID BIGINT,
    DueDate DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Version INT,
    FOREIGN KEY (UserID) REFERENCES User(ID) ON DELETE CASCADE
);  

