CREATE TABLE IF NOT EXISTS PhoneNumber (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    Plaintext VARCHAR(255),
    Hash BINARY(60),
    UserID BIGINT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Version INT,
    FOREIGN KEY (UserID) REFERENCES User(ID) ON DELETE CASCADE
);

