CREATE TABLE IF NOT EXISTS User (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    Email VARCHAR(255) NOT NULL UNIQUE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Scope INT,
    IsActive BOOLEAN,
    Version INT
);

CREATE INDEX idx_user_email ON User(Email);
